resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Default
  steps:
  - checkout: self
    clean: true
  - task: Application security testing@2021
    displayName: Application security testing
    inputs:
      projectName: New_Project1
      enableSastScan: false
      CheckmarxService: 929ae9ce-5340-4677-897c-6bfc53da82af
      fullTeamName: '\CxServer'
      enableDependencyScan: true
      CheckmarxServiceForSca: 'ScaWithoutAgent_YAML'
      scaTeam: '\CxServer'
