resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Default
  steps:
  - checkout: self
    clean: true
  - task: Application security testing@2021
    displayName: Application security testing
    inputs:
      projectName: New_Project1
      enableSastScan: false
      enableDependencyScan: true
      CheckmarxServiceForSca: 'ScaWithoutAgent_YAML'
      scaTeam: '\CxServer'
