resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Default
  steps:
  - checkout: self
    clean: true
  - task: Application security testing@2021
    displayName: Application security testing
    inputs:
      projectName: Project_Pipeline3_SCA
      enableSastScan: false
      CheckmarxService: 347b7bda-704c-4b8d-be9b-70e8523a646f
      fullTeamName: '\CxServer'
      enableDependencyScan: true
      dependencyServerURL: 3a5525c4-15a6-47aa-99b2-370e73c8a7e2
      dependencyTenant: Plugins
      scaTeam: '\CxServer'
...
